In [2]:
import torch
import torch.nn as nn
import math

In [13]:
class LinearLayer(nn.Module):
    def __init__(self, bias=True,dropout=0.5):
        super().__init__()
        #self.layers = []
        self.dropout = dropout
        self.fc1 = self.linear(2,1,bias)
        #self.fc2 = self.linear(4,1,bias)
        
    def linear(self,inputs,outputs,bias):
        
        self.weight = torch.nn.Parameter(torch.randn(outputs, inputs))
        #self.register_parameter('weight', self.weight)
        #print(self.weight)
        if bias:
            self.bias = torch.nn.Parameter(torch.randn(outputs))
            #self.register_parameter('bias', self.bias)
        else:
            self.register_parameter('bias', None)
        #self.layers.append({'w':self.weight,'b':self.bias})
        #print(self.layers)
        return lambda x : torch.add(torch.mm(x, self.weight.t()), self.bias)
    
    def forward(self, x, useDropout):
        if useDropout:
            x = self.dropoutLayer(x)
        x = self.fc1(x)
        #x = torch.relu(x)
        #print('x after relu: ',x)
        #x = self.fc2(x)
        x = torch.sigmoid(x)
        #print('x after sigmoid fc2: ',x)
        return x
    
    def dropoutLayer(self,x):
            input_feature = x.shape[0]
            output_feature = x.shape[1]
            dropoutMat = torch.randn(input_feature,output_feature)
            dropoutMat = dropoutMat < self.dropout
            #print('dropoutMat: ',dropoutMat)
            #print('x before dropout: ',x)
            x = torch.mul(x, dropoutMat)
            x = x/self.dropout #scaling the value cause during testing we will not using dropout & thus passing higher values
            #print('x after dropout: ',x)
            return x
    

In [14]:
net = LinearLayer(bias=True)

In [15]:
x = torch.randn(5,2,requires_grad=True)
y = torch.randn(5,1)
xTest = torch.randn(5,2,requires_grad = True).float()
learning_rate = 0.01
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate)
#print(net.parameters())
# for name, param in enumerate(net.parameters()):
#     if param.requires_grad:
#         print(name, param.data)
for epoch in range(5000):
    y_pred = net(x,True)
    print(y_pred)
    loss = criterion(y_pred,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    #print('loss: ', x.grad)


tensor([[0.2459],
        [0.2998],
        [0.3451],
        [0.5789],
        [0.2709]], grad_fn=<SigmoidBackward>)
tensor([[0.3027],
        [0.3429],
        [0.6899],
        [0.3119],
        [0.2664]], grad_fn=<SigmoidBackward>)
tensor([[0.3014],
        [0.2900],
        [0.3017],
        [0.5393],
        [0.2650]], grad_fn=<SigmoidBackward>)
tensor([[0.2302],
        [0.3292],
        [0.2975],
        [0.5314],
        [0.2631]], grad_fn=<SigmoidBackward>)
tensor([[0.2254],
        [0.3237],
        [0.6616],
        [0.5245],
        [0.3361]], grad_fn=<SigmoidBackward>)
tensor([[0.3339],
        [0.2758],
        [0.6966],
        [0.5589],
        [0.2593]], grad_fn=<SigmoidBackward>)
tensor([[0.3317],
        [0.2715],
        [0.6874],
        [0.5063],
        [0.3140]], grad_fn=<SigmoidBackward>)
tensor([[0.2941],
        [0.3731],
        [0.6772],
        [0.4964],
        [0.2731]], grad_fn=<SigmoidBackward>)
tensor([[0.2376],
        [0.3012],
        [0.6126],
  

In [16]:
#testSet = torch.tensor(xTest,requires_grad = True).float()
with torch.no_grad():
    result = net(xTest,False)
print(result)

tensor([[3.2264e-02],
        [4.5604e-06],
        [1.3348e-04],
        [2.3922e-03],
        [3.1466e-02]])
